### ISSUE TITLE
Create db ERD and Implement it to Oracle DB and add DDL (.sql) script to folder /db on repo

### ISSUE THREAD

**Issue by eltntawy** [DinaAshrafElsayed/GPproject#3]
DB Tables:
##### 1. T_User 
- id (pk, integer)
- username(nn,varchar(20) 
- email(unq, varchar(100)
- Address  (another table)
- password(byte)
  - gender (in other table or an enum in user class can mapped values from 0/1 to “male/female”)
  - image-url(varchar(200)
  - points(integer).

##### 5.T_Address
- id (integer)
- user (user)
- country (other lookup table)
- city (other lookup table)
- State (other lookup table)

##### 2.T_Item
- id
 - name (vch(20))
 - description (vch(200))
 - category (another table)
 - is_available (bool)
 - publish_date(sysdate).
 - points

#####  3.T_Category
  - id (integer)
  - name (vch(200))
  - max_point (integer)

##### 4.T_Activity
  - id (integer)
  - item (item)
  - from_user (user)
  - to_user (user)
  - meeting_point (vch(200))
  - status (can be another table or enum)
  - time_from (date)
  - time_to (date)
  - activity_deleted(bool)

**Comment by eltntawy** [comment]
@adelzaid4 please add (mandatory fields to be not null, unique constraints )

**Comment by adelzaid4** [comment]
Note:
(bool) type isn't supported in ORACLE, instead I defined Boolean columns as char and we'll refer to it as (Y/N)

**Comment by eltntawy** [comment]
@adelzaid4, please make them byte or int to value (0 false /1 ture) to hibernate can map it automatically to Boolean 

and sorry i forget to add points in item table so please add [T_Item.points] to table

**Comment by adelzaid4** [comment]
Done
